### ISSUE TITLE
DB connection closed in the middle of an operation

### ISSUE THREAD

**Issue by DTS-11** [DTS-11/PizzaHat#46]
The complete error from logging:
```cmd
ERROR      - 2024-01-28 13:45:56,523 - client          : Ignoring exception in on_message_edit
Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py", line 286, in _loop_reading
    length = fut.result()
             ^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 846, in _poll
    value = callback(transferred, key, ov)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 494, in finish_recv
    return ov.getresult()
           ^^^^^^^^^^^^^^
OSError: [WinError 121] The semaphore timeout period has expired

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\Projects\PizzaHat\PizzaHat\utils\events.py", line 105, in on_message_edit
    channel = await self.get_logs_channel(before.guild.id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\PizzaHat\PizzaHat\utils\events.py", line 77, in get_logs_channel
    data = await self.bot.db.fetchval("SELECT channel_id FROM modlogs WHERE guild_id=$1", guild_id)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\asyncpg\pool.py", line 608, in fetchval
    async with self.acquire() as con:
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\asyncpg\pool.py", line 1005, in __aexit__
    await self.pool.release(con)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\asyncpg\pool.py", line 879, in release
    return await asyncio.shield(ch.release(timeout))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\asyncpg\pool.py", line 220, in release
    raise ex
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\asyncpg\pool.py", line 210, in release
    await self._con.reset(timeout=budget)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\asyncpg\connection.py", line 1366, in reset
    await self.execute(reset_query, timeout=timeout)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\asyncpg\connection.py", line 317, in execute
    return await self._protocol.query(query, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg\protocol\protocol.pyx", line 338, in query
asyncpg.exceptions.ConnectionDoesNotExistError: connection was closed in the middle of operation
```

**Comment by DTS-11** [comment]
solved
